#define create_opt(opt) create(opt)
#define create_const(name) create(kOptConst, (name))
#define create_var(name) create(kOptVar, (name))
#define create_func(name) create(kOptFunc, (name))

#define minus(s) make(kOptSub, s)
#define add(s1, s2) make(kOptAdd, s1, s2)
#define sub(s1, s2) make(kOptSub, s1, s2)
#define mul(s1, s2) make(kOptMul, s1, s2)
#define div(s1, s2) make(kOptDiv, s1, s2)
#define mod(s1, s2) make(kOptMod, s1, s2)
#define sqrt(s) make(kOptSqrt, s)
#define exp(s, e) make(kOptExp, s, e)
#define log(b, s) make(kOptLog, b, s)
#define frac(n, d) make(kOptFrac, n, d)
#define sin(s) make(kOptSin, s)
#define cos(s) make(kOptCos, s)
#define tan(s) make(kOptTan, s)
#define cot(s) make(kOptCot, s)
#define sec(s) make(kOptSec, s)
#define csc(s) make(kOptCsc, s)
#define asin(s) make(kOptArcSin, s)
#define acos(s) make(kOptArcCos, s)
#define atan(s) make(kOptArcTan, s)
#define acot(s) make(kOptArcCot, s)
#define asec(s) make(kOptArcSec, s)
#define acsc(s) make(kOptArcCsc, s)
#define sinh(s) make(kOptSinh, s)
#define cosh(s) make(kOptCosh, s)
#define tanh(s) make(kOptTanh, s)
#define coth(s) make(kOptCoth, s)
#define sech(s) make(kOptSech, s)
#define csch(s) make(kOptCsch, s)
#define asinh(s) make(kOptArcSinh, s)
#define acosh(s) make(kOptArcCosh, s)
#define atanh(s) make(kOptArcTanh, s)
#define acoth(s) make(kOptArcCoth, s)
#define asech(s) make(kOptArcSech, s)
#define acsch(s) make(kOptArcCsch, s)

//
// 字符串创建
//
#define minus_(s) make_(kOptSub, s)
#define add_(s1, s2) make_(kOptAdd, s1, s2)
#define sub_(s1, s2) make_(kOptSub, s1, s2)
#define mul_(s1, s2) make_(kOptMul, s1, s2)
#define div_(s1, s2) make_(kOptDiv, s1, s2)
#define mod_(s1, s2) make_(kOptMod, s1, s2)
#define sqrt_(s) make_(kOptSqrt, s)
#define exp_(s, e) make_(kOptExp, s, e)
#define log_(b, s) make_(kOptLog, b, s)
#define frac_(n, d) make_(kOptFrac, n, d)
#define sin_(s) make_(kOptSin, s)
#define cos_(s) make_(kOptCos, s)
#define tan_(s) make_(kOptTan, s)
#define cot_(s) make_(kOptCot, s)
#define sec_(s) make_(kOptSec, s)
#define csc_(s) make_(kOptCsc, s)
#define asin_(s) make_(kOptArcSin, s)
#define acos_(s) make_(kOptArcCos, s)
#define atan_(s) make_(kOptArcTan, s)
#define acot_(s) make_(kOptArcCot, s)
#define asec_(s) make_(kOptArcSec, s)
#define acsc_(s) make_(kOptArcCsc, s)
#define sinh_(s) make_(kOptSinh, s)
#define cosh_(s) make_(kOptCosh, s)
#define tanh_(s) make_(kOptTanh, s)
#define coth_(s) make_(kOptCoth, s)
#define sech_(s) make_(kOptSech, s)
#define csch_(s) make_(kOptCsch, s)
#define asinh_(s) make_(kOptArcSinh, s)
#define acosh_(s) make_(kOptArcCosh, s)
#define atanh_(s) make_(kOptArcTanh, s)
#define acoth_(s) make_(kOptArcCoth, s)
#define asech_(s) make_(kOptArcSech, s)
#define acsch_(s) make_(kOptArcCsch, s)
